[2024-10-26T16:01:49.167+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.transform_data manual__2024-10-26T16:01:09.677419+00:00 [queued]>
[2024-10-26T16:01:49.180+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.transform_data manual__2024-10-26T16:01:09.677419+00:00 [queued]>
[2024-10-26T16:01:49.181+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-26T16:01:49.344+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_data> on 2024-10-26 16:01:09.677419+00:00
[2024-10-26T16:01:49.353+0000] {standard_task_runner.py:57} INFO - Started process 7896 to run task
[2024-10-26T16:01:49.357+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transform_data', 'manual__2024-10-26T16:01:09.677419+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpyai9utz3']
[2024-10-26T16:01:49.361+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask transform_data
[2024-10-26T16:01:49.692+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_dag.transform_data manual__2024-10-26T16:01:09.677419+00:00 [running]> on host 0ca1d6ea2b5f
[2024-10-26T16:01:50.442+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T16:01:09.677419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T16:01:09.677419+00:00'
[2024-10-26T16:01:50.443+0000] {logging_mixin.py:150} INFO - Начало выполнения transform_data
[2024-10-26T16:01:50.443+0000] {logging_mixin.py:150} INFO - Ошибка: Can only merge Series or DataFrame objects, a <class 'str'> was passed
[2024-10-26T16:01:50.444+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-26T16:01:50.455+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=transform_data, execution_date=20241026T160109, start_date=20241026T160149, end_date=20241026T160150
[2024-10-26T16:01:50.482+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-26T16:01:50.514+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
